stages:
- test
- build
- ship
- deploy
cache:
  untracked: true
  key: ${CI_BUILD_REF}_${CI_BUILD_REF_NAME}
job_demoFeature_build:
  stage: build
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_NODE}
  tags:
  - ued
  environment:
    name: UED-DEMO
  script:
  - project run build
  only:
  - /^demo/feature\/.*$/
job_demoFeature_deploy:
  stage: deploy
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_RANCHER}
  tags:
  - ued
  environment:
    name: UED-DEMO
  script:
  - project deploy
  only:
  - /^demo/feature\/.*$/
job_demoFeature_ship:
  stage: ship
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_DOCKER}
  tags:
  - ued
  environment:
    name: UED-DEMO
  script:
  - project ship --push
  only:
  - /^demo/feature\/.*$/
job_feature_build:
  stage: build
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_NODE}
  tags:
  - ued
  environment:
    name: UED-TEST
  script:
  - project run build
  only:
  - /^feature\/.*$/
job_feature_deploy:
  stage: deploy
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_RANCHER}
  tags:
  - ued
  environment:
    name: UED-TEST
  script:
  - RANCHER_ENVIRONMENT=UED-TEST rancher-env.sh project deploy
  only:
  - /^feature\/.*$/
job_feature_ship:
  stage: ship
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_DOCKER}
  tags:
  - ued
  environment:
    name: UED-TEST
  script:
  - project ship --push
  only:
  - /^feature\/.*$/
job_feature_test:
  stage: test
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_NODE}
  tags:
  - ued
  environment:
    name: UED-TEST
  script:
  - project run test
  only:
  - /^feature\/.*$/
job_master_build:
  stage: build
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_NODE}
  tags:
  - ued
  environment:
    name: UED-DEMO
  script:
  - project run build
  only:
  - master
job_master_deploy:
  stage: deploy
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_RANCHER}
  tags:
  - ued
  environment:
    name: UED-DEMO
  script:
  - RANCHER_ENVIRONMENT=UED-DEMO rancher-env.sh project deploy
  only:
  - master
job_master_ship:
  stage: ship
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_DOCKER}
  tags:
  - ued
  environment:
    name: UED-DEMO
  script:
  - project ship --push
  only:
  - master
job_testFeature_build:
  stage: build
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_NODE}
  tags:
  - ued
  environment:
    name: UED-TEST
  script:
  - project run build
  only:
  - /^test/feature\/.*$/
job_testFeature_deploy:
  stage: deploy
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_RANCHER}
  tags:
  - ued
  environment:
    name: UED-TEST
  script:
  - project deploy
  only:
  - /^test/feature\/.*$/
job_testFeature_ship:
  stage: ship
  image: ${G7PAY_DOCKER_REGISTRY}/${BUILDER_DOCKER}
  tags:
  - ued
  environment:
    name: UED-TEST
  script:
  - project ship --push
  only:
  - /^test/feature\/.*$/