language: node_js
node_js:
    - '8.9.1'

cache: npm

# S: Build Lifecycle
install:
  - npm install

script:
  - npm run build

github_token: ${USER_TOKEN}

after_script:
  - cd ./dist
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "am-ui"
  - git push --force --quiet "https://${USER_TOKEN}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle

# 只对某个分支行为生效
branches:
  only:
    - master